# This is a basic workflow to help you get started with Actions

name: CI pushDocs

# Controls when the workflow will run
on:
  # 配置當PUSH進入什麼分支的時候執行
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 具體的執行步驟
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 使用的node版本   
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      
      # 執行安装
      - name: Install dependencies
        run: npm install
        
      # 執行打包
      - name: Build VuePress
        run: npm run docs:build
        
      # 執行部屬
      - name: Deploy to Pages
        run: |
          cd docs/.vuepress/dist
          git init
          git config user.name "arx827"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://arx827:${{ secrets.ACCESS_TOKEN }}@github.com/arx827/gundam-review.git master:gh-pages
          cd -
